apiVersion: batch/v1
kind: Job
metadata:
  name: webapp-job
  labels:
    name: webapp
spec:
  completions: 1
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        name: webapp
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: registrypullsecret
      containers:
      - name: cve-processor-container
        image: eashanroy7866/cve-processor:1.0.0
        env:
        - name: kafka_host
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: kafka_host
        - name: kafka_port
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: kafka_port