apiVersion: batch/v1
kind: Job
metadata:
  name: webapp-job
  labels:
    name: webapp
spec:
  completions: 1
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        name: webapp
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: registrypullsecret
      containers:
      - name: cve-processor-container
        image: eashanroy7866/cve-processor:1.0.0
        env:
        - name: db_name
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db_name
        - name: db_host
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db_host
        - name: db_user
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db_user
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db_password
        - name: db_port
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db_port
      initContainers:
      - name: db-migration-container
        image: eashanroy7866/db-migration:1.0.0
        volumeMounts: 
        - name: flyway-config
          mountPath: /flyway/conf/flyway.conf
          subPath: flyway.conf
          readOnly: true
      volumes: 
      - name: flyway-config
        configMap:
          name: flyway-config
