apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Values.job.name}}
  namespace: {{.Values.namespace}}
  {{ include "webapp-job.labels" . | nindent 2 }}
spec:
  completions: 1
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      {{ include "webapp-job.labels" . | nindent 6 }}
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: registrypullsecret
      containers:
      - name: {{.Values.container.name}}
        image: {{.Values.container.image}}
        resources:
          requests:
            memory: "1700Mi"
            cpu: "1500m"
          limits:
            memory: "2500Mi"
            cpu: "2000m"
        imagePullPolicy: Always
        env:
        - name: kafka_host
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: kafka_host
        - name: kafka_port
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: kafka_port
        - name: kafka_topic
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: kafka_topic