---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.pod.name }}
  {{ include "cve-processor.labels" . | nindent 2 }}
spec:
  hostNetwork: true
  containers:
  - name: cve-processor-container
    image: {{.Values.image.cveprocessor}}
    volumeMounts:
      - name: app-secret
        mountPath: /app/.env
        readOnly: true
    env:
    - name: flyway_schemas
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: flyway_schemas
  initContainers:
  - name: db-migration-container
    image: {{.Values.image.initContainer}}
    volumeMounts:
      - name: app-secret
        mountPath: /app/.env
        readOnly: true
    env:
    - name: flyway_schemas
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: flyway_schemas
  volumes:
    - name: app-secret
      secret:
        secretName: app-secret
