---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    name: webapp
spec:
  hostNetwork: true
  containers:
  - name: cve-processor-container
    image: eashanroy7866/cve-processor:latest
    volumeMounts:
      - name: app-secret
        mountPath: /app/.env
        readOnly: true
    env:
    - name: flyway_schemas
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: flyway_schemas
  initContainers:
  - name: db-migration-container
    image: eashanroy7866/db-migration:latest
    volumeMounts:
      - name: app-secret
        mountPath: /app/.env
        readOnly: true
    env:
    - name: flyway_schemas
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: flyway_schemas
  volumes:
    - name: app-secret
      secret:
        secretName: app-secret
