apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres-service
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres-container
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          valueFrom: 
            secretKeyRef:
              name: app-secret
              key: db_user
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: app-secret
              key: db_password
        - name: POSTGRES_DB
          valueFrom: 
            secretKeyRef:
              name: app-secret
              key: db_name
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: data-volume
          mountPath: /var/lib/postgesql/data
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: ebs-storage-class
      resources:
        requests:
          storage: 5Gi
